# Generated by Django 6.0.7 on 2026-07-19 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('pairing_ids', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=10)),
                ('n_answers', models.PositiveIntegerField(default=0)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=64, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('calibration_stats', models.JSONField(blank=True, default=dict)),
                ('weight', models.FloatField(default=1.0, help_text='Baseline weight; 0 excludes silently.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.FloatField()),
                ('width_left', models.FloatField()),
                ('width_right', models.FloatField()),
                ('response_ms', models.PositiveIntegerField()),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='core.pairing')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_points', models.FloatField()),
                ('crps', models.FloatField(blank=True, null=True)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core.guess')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_label', models.CharField(max_length=60)),
                ('right_label', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='pairing',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='core.scale'),
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=10)),
                ('language', models.CharField(default='en', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='things', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='pairing',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='core.thing'),
        ),
        migrations.CreateModel(
            name='DistributionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram', models.JSONField()),
                ('median', models.FloatField()),
                ('q25', models.FloatField()),
                ('q75', models.FloatField()),
                ('n', models.PositiveIntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.pairing')),
            ],
            options={
                'get_latest_by': 'computed_at',
                'indexes': [models.Index(fields=['pairing', '-computed_at'], name='core_distri_pairing_998fa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=40)),
                ('histogram', models.JSONField()),
                ('median', models.FloatField()),
                ('q25', models.FloatField()),
                ('q75', models.FloatField()),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_distributions', to='core.pairing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pairing', 'model_name', 'prompt_version'), name='unique_ai_estimate_per_model_and_prompt')],
            },
        ),
        migrations.AddIndex(
            model_name='guess',
            index=models.Index(fields=['pairing', 'created_at'], name='core_guess_pairing_46d601_idx'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.CheckConstraint(condition=models.Q(('center__gte', 0), ('center__lte', 100)), name='guess_center_on_scale'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.CheckConstraint(condition=models.Q(('width_left__gte', 0), ('width_right__gte', 0)), name='guess_widths_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='pairing',
            constraint=models.UniqueConstraint(fields=('thing', 'scale'), name='unique_thing_scale'),
        ),
    ]
