# Generated by Django 6.0.7 on 2026-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="hot_streak",
            field=models.PositiveIntegerField(
                default=0, help_text="Consecutive good rounds."
            ),
        ),
    ]
