# Generated by Django 6.0.7 on 2026-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_player_hot_streak"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="daily_streak",
            field=models.PositiveIntegerField(
                default=0, help_text="Consecutive days played."
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="last_played_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="streak_freezes",
            field=models.PositiveIntegerField(
                default=0, help_text="Missed-day protections."
            ),
        ),
    ]
