# Generated by Django 6.0.7 on 2026-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_player_daily_streak_player_last_played_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pairing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("rejected", "Rejected"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="scale",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("rejected", "Rejected"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="thing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("rejected", "Rejected"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
