# Generated by Django 6.0.7 on 2026-07-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_pairing_status_alter_scale_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWaveEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("visible_points", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guess",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_wave_entry",
                        to="core.guess",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_wave_entries",
                        to="core.player",
                    ),
                ),
                (
                    "wave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.dailywave",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wave", "player", "index"),
                        name="unique_daily_wave_slot",
                    )
                ],
            },
        ),
    ]
