# Generated by Django 6.0.7 on 2026-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_dailywaveentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="xp_multiplier",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Calibration multiplier (×1–×10); grows on well-covered rounds.",
            ),
        ),
    ]
