# Generated by Django 6.0.7 on 2026-07-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_player_xp_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairing",
            name="voting_disabled",
            field=models.BooleanField(
                default=False,
                help_text="Exclude from the fun/boring vote (admin or auto-flagged).",
            ),
        ),
        migrations.CreateModel(
            name="PairingVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("fun", "Fun"),
                            ("interesting", "Interesting"),
                            ("boring", "Boring"),
                            ("weird", "Weird"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_votes",
                        to="core.player",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_votes",
                        to="core.scale",
                    ),
                ),
                (
                    "thing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_votes",
                        to="core.thing",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "thing", "scale"),
                        name="one_vote_per_player_and_pairing",
                    )
                ],
            },
        ),
    ]
