# Generated by Django 6.0.7 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_pairing_voting_disabled_pairingvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_scale_request_on",
            field=models.DateField(
                blank=True,
                help_text="Day of the player's last scale request (once/day).",
                null=True,
            ),
        ),
    ]
