# Generated by Django 6.0.7 on 2026-07-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_player_last_scale_request_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetStats",
            fields=[],
            options={
                "verbose_name": "Research statistic",
                "verbose_name_plural": "Research statistics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.pairing",),
        ),
    ]
