# Generated by Django 6.0.7 on 2026-07-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_datasetstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributionsnapshot",
            name="belief_histogram",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
