# Generated by Django 6.0.7 on 2026-08-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_backfill_belief_histograms"),
    ]

    operations = [
        migrations.CreateModel(
            name="PvpMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_code", models.CharField(max_length=64, unique=True)),
                ("pairing_ids", models.JSONField(default=list)),
                ("invited_email", models.CharField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvp_matches_started",
                        to="core.player",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvp_matches_joined",
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PvpEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "visible_points",
                    models.FloatField(help_text="Round score after any speed bonus."),
                ),
                ("means_match", models.FloatField(default=0.0)),
                ("belief_match", models.FloatField(default=0.0)),
                ("response_ms", models.PositiveIntegerField(default=0)),
                (
                    "speed_bonus",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this round's points were doubled.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guess",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvp_entry",
                        to="core.guess",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvp_entries",
                        to="core.player",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.pvpmatch",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "player", "index"),
                        name="unique_pvp_match_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PvpRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("challenger_ready_at", models.DateTimeField(blank=True, null=True)),
                ("opponent_ready_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="core.pvpmatch",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "index"), name="unique_pvp_round_slot"
                    )
                ],
            },
        ),
    ]
